services:
  - type: web
    name: hrm-backend
    runtime: docker
    plan: free
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: ""   # để trống vì Dockerfile đã define ENTRYPOINT
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
